### ALIASES
alias va="vim ~/.dotfiles/aliases.zsh"
alias vp="vim ~/.dotfiles/packages.zsh"
alias vf="vim ~/.dotfiles/functions.zsh"
alias vt="vim ~/.dotfiles/themes/cswenberg.zsh-theme"
alias zsrc="source ~/.zshrc"

# System
alias lsa="ls -a"
alias rmdir="rm -rf"

# Git
alias gs="git status"
alias gd="git diff"
alias gb="git branch"
alias gpl="git pull"
alias gl="git log"
alias glo="git log --oneline"
alias ga="git add"
alias gaa="git add ."
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gph="git push"
alias gup="git push --set-upstream origin"
alias gck="git checkout"
alias gcb="git checkout -b"
alias gckm="git checkout main"
alias gr="git rebase"
alias grm="git rebase main"
alias grc="git rebase --continue"
alias grs="git restore"
alias grss="git restore --staged"
alias gm="git mv"
alias gsh="git stash"

# Dapp tools
alias db="dapp build"
alias dt="dapp test"
alias dtm="dapp test -m"
alias dtg="dapp test -m 'Gas'"
alias dreset="rm -rf ~/.dapp/testnet/8545"
