### ALIASES
alias va="vim ~/.dotfiles/core-aliases.zsh"
alias vap="vim ~/.dotfiles/protocol-aliases.zsh"
alias vaw="vim ~/.dotfiles/web-aliases.zsh"
alias vp="vim ~/.dotfiles/packages.zsh"
alias vf="vim ~/.dotfiles/functions.zsh"
alias vt="vim ~/.dotfiles/themes/cswenberg.zsh-theme"
alias zsrc="source ~/.zshrc"

# System
alias lsa="ls -a"
alias rmdir="rm -rf"

# Git
alias gs="git status"
alias gd="git diff"
alias gb="git branch"
alias gbwipe="git branch | grep -v 'main' | xargs git branch -D"
alias gpl="git pull"
alias gl="git log"
alias glo="git log --oneline"
alias ga="git add"
alias gaa="git add ."
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gcp="git cherry-pick"
alias gph="git push"
alias gup="git push --set-upstream origin"
alias gck="git checkout"
alias gcb="git checkout -b"
alias gckm="git checkout main"
alias gckp="git checkout feature/proposals"
alias gr="git rebase"
alias grm="git rebase main"
alias grc="git rebase --continue"
alias grs="git restore"
alias grss="git restore --staged"
alias gsm="git submodule"
alias gsma="git submodule add"
alias gm="git mv"
alias gsh="git stash"

